<?php
declare(strict_types=1);require_once __DIR__.'/pg_connection.php';
class ProductService{
 private PDO $db;public function __construct(){$this->db=pg_pool();}private function company():int{return (int)($_SESSION['empresa_id']??0);}
 public function list(int $page=1,int $perPage=10,string $orderBy='id',string $direction='DESC'):array{$allowed=['id','codigo_producto','nombre_producto','precio_venta','stock_actual'];if(!in_array($orderBy,$allowed,true))$orderBy='id';$direction=strtoupper($direction)==='ASC'?'ASC':'DESC';$offset=max(0,($page-1)*$perPage);$s=$this->db->prepare("SELECT * FROM dte_productos WHERE borrado_logico=0 AND company_id=? ORDER BY $orderBy $direction LIMIT ? OFFSET ?");$s->bindValue(1,$this->company(),PDO::PARAM_INT);$s->bindValue(2,$perPage,PDO::PARAM_INT);$s->bindValue(3,$offset,PDO::PARAM_INT);$s->execute();$c=$this->db->prepare('SELECT COUNT(*) FROM dte_productos WHERE borrado_logico=0 AND company_id=?');$c->execute([$this->company()]);return ['success'=>true,'data'=>$s->fetchAll(),'total'=>(int)$c->fetchColumn()];}
 public function get(int $id):array{$s=$this->db->prepare('SELECT * FROM dte_productos WHERE id=? AND company_id=? LIMIT 1');$s->execute([$id,$this->company()]);return ['success'=>true,'data'=>$s->fetch()?:null];}
 public function getById(int $id):array{return $this->get($id);}
 public function getByBarcode(string $barcode):array{$s=$this->db->prepare('SELECT * FROM dte_productos WHERE codigo_barras=? AND company_id=? AND borrado_logico=0 LIMIT 1');$s->execute([$barcode,$this->company()]);return ['success'=>true,'data'=>$s->fetch()?:null];}
 public function create(array $data):array{$s=$this->db->prepare('INSERT INTO dte_productos (company_id,codigo_producto,codigo_barras,nombre_producto,descripcion,precio_venta,precio_compra,stock_actual,stock_minimo,borrado_logico) VALUES (?,?,?,?,?,?,?,?,?,0)');$s->execute([$this->company(),$data['codigo_producto']??null,$data['codigo_barras']??null,$data['nombre_producto']??'', $data['descripcion']??null,(float)($data['precio_venta']??0),(float)($data['precio_compra']??0),(float)($data['stock_actual']??0),(float)($data['stock_minimo']??0)]);return ['success'=>true,'data'=>$this->get((int)$this->db->lastInsertId())['data']];}
 public function update(int $id,array $data):array{$s=$this->db->prepare('UPDATE dte_productos SET codigo_barras=?,nombre_producto=?,descripcion=?,precio_venta=?,precio_compra=?,stock_actual=?,stock_minimo=?,actualizado_el=CURRENT_TIMESTAMP WHERE id=? AND company_id=?');$s->execute([$data['codigo_barras']??null,$data['nombre_producto']??'', $data['descripcion']??null,(float)($data['precio_venta']??0),(float)($data['precio_compra']??0),(float)($data['stock_actual']??0),(float)($data['stock_minimo']??0),$id,$this->company()]);return ['success'=>true,'data'=>$this->get($id)['data']];}
 public function delete(int $id):array{$s=$this->db->prepare('UPDATE dte_productos SET borrado_logico=1 WHERE id=? AND company_id=?');$s->execute([$id,$this->company()]);return ['success'=>true,'affected'=>$s->rowCount()];}
}
